# Generated by Django 6.0 on 2025-12-10 22:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('rut', models.CharField(max_length=15, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True)),
                ('contacto_principal', models.CharField(blank=True, max_length=200, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('modelo', models.CharField(blank=True, max_length=100, null=True)),
                ('serie', models.CharField(blank=True, max_length=100, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.CharField(choices=[('operativo', 'Operativo'), ('mantenimiento', 'En Mantenimiento'), ('reparacion', 'En Reparación'), ('fuera_servicio', 'Fuera de Servicio'), ('inactivo', 'Inactivo')], default='operativo', max_length=20)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('critical', models.BooleanField(default=False, help_text='Indica si es equipo crítico')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='mantenimiento.empresa')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['empresa', 'nombre'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('especialidad', models.CharField(choices=[('mecanico', 'Mecánico'), ('electrico', 'Eléctrico'), ('hidraulico', 'Hidráulico'), ('electromecanico', 'Electromecánico'), ('general', 'General'), ('otro', 'Otro')], max_length=20)),
                ('experiencia_anos', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('certificaciones', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_contratacion', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresas', models.ManyToManyField(blank=True, related_name='tecnicos', to='mantenimiento.empresa')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('predictivo', 'Predictivo')], default='preventivo', max_length=20)),
                ('frecuencia', models.CharField(choices=[('diaria', 'Diaria'), ('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('otro', 'Otro')], max_length=20)),
                ('frequency_days', models.IntegerField(default=30, help_text='Frecuencia en días')),
                ('duracion_estimada_horas', models.DecimalField(decimal_places=2, default=1, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('tareas', models.TextField()),
                ('herramientas_requeridas', models.TextField(blank=True, null=True)),
                ('repuestos_comunes', models.TextField(blank=True, null=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='mantenimiento.empresa')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='mantenimiento.equipo')),
                ('tecnicos_recomendados', models.ManyToManyField(blank=True, related_name='planes', to='mantenimiento.tecnico')),
            ],
            options={
                'verbose_name': 'Plan de Mantenimiento',
                'verbose_name_plural': 'Planes de Mantenimiento',
                'ordering': ['empresa', 'equipo', 'nombre'],
                'unique_together': {('equipo', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_progreso', 'En Progreso'), ('pausada', 'Pausada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('pendiente', 'Pendiente')], default='programada', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=20)),
                ('fecha_programada', models.DateTimeField()),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_termino', models.DateTimeField(blank=True, null=True)),
                ('horas_trabajadas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('repuestos_utilizados', models.TextField(blank=True, null=True)),
                ('costo_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='mantenimiento.empresa')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to='mantenimiento.equipo')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='mantenimiento.plan')),
                ('tecnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes', to='mantenimiento.tecnico')),
            ],
            options={
                'verbose_name': 'Orden de Trabajo',
                'verbose_name_plural': 'Órdenes de Trabajo',
                'ordering': ['-fecha_programada'],
            },
        ),
    ]
